// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TracIT;

#nullable disable

namespace Trac_IT.Migrations
{
    [DbContext(typeof(TracITDbContext))]
    [Migration("20231129013846_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IssueUser", b =>
                {
                    b.Property<int>("issuesissueId")
                        .HasColumnType("integer");

                    b.Property<int>("usersId")
                        .HasColumnType("integer");

                    b.HasKey("issuesissueId", "usersId");

                    b.HasIndex("usersId");

                    b.ToTable("IssueUser");
                });

            modelBuilder.Entity("TracIT.Models.Comment", b =>
                {
                    b.Property<int>("commentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("commentId"));

                    b.Property<string>("commentText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("issueId")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("commentId");

                    b.HasIndex("issueId");

                    b.HasIndex("userId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("TracIT.Models.Issue", b =>
                {
                    b.Property<int>("issueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("issueId"));

                    b.Property<DateTime>("dateTimeCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("statusId")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("issueId");

                    b.HasIndex("statusId");

                    b.ToTable("Issues");

                    b.HasData(
                        new
                        {
                            issueId = 1,
                            dateTimeCreated = new DateTime(2023, 11, 28, 20, 38, 46, 384, DateTimeKind.Local).AddTicks(6492),
                            description = "Create modal for entering new issue",
                            statusId = 1,
                            title = "Create Modal"
                        });
                });

            modelBuilder.Entity("TracIT.Models.Status", b =>
                {
                    b.Property<int>("statusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("statusId"));

                    b.Property<string>("statusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("statusId");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            statusId = 1,
                            statusName = "New"
                        },
                        new
                        {
                            statusId = 2,
                            statusName = "Active"
                        },
                        new
                        {
                            statusId = 3,
                            statusName = "Closed"
                        });
                });

            modelBuilder.Entity("TracIT.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IssueUser", b =>
                {
                    b.HasOne("TracIT.Models.Issue", null)
                        .WithMany()
                        .HasForeignKey("issuesissueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TracIT.Models.User", null)
                        .WithMany()
                        .HasForeignKey("usersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TracIT.Models.Comment", b =>
                {
                    b.HasOne("TracIT.Models.Issue", "issue")
                        .WithMany()
                        .HasForeignKey("issueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TracIT.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("issue");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TracIT.Models.Issue", b =>
                {
                    b.HasOne("TracIT.Models.Status", "status")
                        .WithMany()
                        .HasForeignKey("statusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("status");
                });
#pragma warning restore 612, 618
        }
    }
}
